#!/usr/bin/python3

import time
import logging
import sys
import select

from optparse import OptionParser
from euchred import Euchred
from card import Card
from logging import warning as warn, log, debug, info, error, critical


###########################################################################
# This returns true if all 4 players are in joined state, false otherwise
#
def allJoined():
    # default to true
    state = False

    # if any player has not joined, set to false
    if     'state' in p0.state[0] and p0.state[0]['state'] == 2 \
       and 'state' in p0.state[1] and p0.state[1]['state'] == 2 \
       and 'state' in p0.state[2] and p0.state[2]['state'] == 2 \
       and 'state' in p0.state[3] and p0.state[3]['state'] == 2:
        state = True

    return state


###########################################################################
# This sends a start message to begin the game: it figures out who the
# creator is and sends a message as that person
#
def sendStart():
    # figure out the creator
    if p0.state[0]['creator'] == 1:
        # send start message
        info("game: p0 is the creator")
        p0.sendStart()
    if p1.state[1]['creator'] == 1:
        # send start message
        info("game: p1 is the creator")
        p1.sendStart()
    if p2.state[2]['creator'] == 1:
        # send start message
        info("game: p2 is the creator")
        p2.sendStart()
    if p3.state[3]['creator'] == 1:
        # send start message
        info("game: p3 is the creator")
        p3.sendStart()

    # set started to 1 to avoid sending multiple starts
    started = 1

###########################################################################
# parse our options

parser = OptionParser()
parser.add_option("-q", "--quiet",
                  dest="quiet",
                  default=False,
                  action="store_true",
                  help="don't print anything to stdout")
(options, args) = parser.parse_args()


###########################################################################
# set up logging

# we have two types of formatters: one for the file (with more detailed
# timing and message levels) and a more compact one for stdout
fhfmt = logging.Formatter(
    fmt="%(asctime)s.%(msecs)03d :: %(levelname)s :: %(message)s",
    datefmt='%Y-%m-%d %H:%M:%S')
chfmt = logging.Formatter(
    fmt="%(asctime)s :: %(message)s",
    datefmt='%Y-%m-%d %H:%M:%S')

# get the root logger
logger = logging.getLogger('')
logger.setLevel(logging.DEBUG)

# make a console handler and add it, if quiet isn't enabled
if not options.quiet:
    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(chfmt)
    logger.addHandler(ch)

# make the logfile handler and add it
fh = logging.FileHandler("leuchre.log",mode="w+")
fh.setFormatter(fhfmt)
logger.addHandler(fh)


###########################################################################
# some other initialization

# we track whether we've sent a start message or not
started = 0

###########################################################################
# mainline

info("This is leuchre")

p0 = Euchred(server="127.0.0.1", port=1234, name="p0")
info("joining server %s on port %d",p0.server,p0.port)
p0.sendJoin()

p1 = Euchred(server="127.0.0.1", port=1234, name="p1")
info("joining server %s on port %d",p1.server,p1.port)
p1.sendJoin()

p2 = Euchred(server="127.0.0.1", port=1234, name="p2")
info("joining server %s on port %d",p2.server,p2.port)
p2.sendJoin()

p3 = Euchred(server="127.0.0.1", port=1234, name="p3")
info("joining server %s on port %d",p3.server,p3.port)
p3.sendJoin()

# now we loop to handle events from the server
inputs = [ p0.s , p1.s , p2.s , p3.s ]

# loop while we still have valid inputs (actually, since we never modify
# the inputs array, we just loop forever)
while inputs:
    readable, writable, exceptional = select.select(inputs, [], inputs)

    # loop across each readable socket
    for s in readable:
        if s is p0.s:
            info("")
            info("got data from server for p0")
            p0.parseMessage()
            p0.status()
        if s is p1.s:
            info("")
            info("got data from server for p1")
            p1.parseMessage()
            p1.status()
        if s is p2.s:
            info("")
            info("got data from server for p2")
            p2.parseMessage()
            p2.status()
        if s is p3.s:
            info("")
            info("got data from server for p3")
            p3.parseMessage()
            p3.status()

    # each time through, we drive game state forward by checking to see
    # the current hand state
    #  - if pregame (0), and all players joined, send start
    #  - if hole (1), then someone has an option to order the hole card
    #  - if trump (2), then someone has an option to call trump
    #  - if defend (3), then someone has an option to defend alone
    #  - if play (4), then someone has an option to play
    # 
    # the game state is sent to all players, but it should be the same
    # for them all, so we check it against player 0, but it would work
    # to check it against any other player too
    if allJoined():
        if p0.state['hstate'] == 0 and started != 1:
            info("game: everyone is joined, sending start")

            # this sends the start message: let the games begin!
            sendStart()
    

# we shouldn't ever get here, but just in case
info("sleeping...")
time.sleep(10000)
